# fly.toml app configuration file generated for frontend-green-flower-3817 on 2025-09-04T06:39:50-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'frontend-green-flower-3817'
primary_region = 'lax'

[build]

[env]
  NEXT_PUBLIC_API_URL = "https://api-dark-flower-4953.fly.dev"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
