estimate_class: "Class 3"          # AACE tagging
overhead_pct: 0.10
profit_pct: 0.10
regional_factor: 1.00

phases:            # UNIFORMAT II (examples)
  - { code: "B20", name: "Exterior Enclosure", contingency_pct: 0.10 }
  - { code: "C30", name: "Interior Finishes",  contingency_pct: 0.10 }
  - { code: "D20", name: "Plumbing (Sub)",     contingency_pct: 0.12 }
  - { code: "D50", name: "Electrical (Sub)",   contingency_pct: 0.12 }

labor_classes:
  - { name: "Laborer",   base_rate: 30.0, burden_pct: 0.45 }
  - { name: "Carpenter", base_rate: 38.0, burden_pct: 0.45 }

productivities:
  - { item_code: "09 30 00", hours_per_unit: 0.12, factors: { access: 1.00, occupied: 1.00 } }  # tile SF
  - { item_code: "09 90 00", hours_per_unit: 0.06, factors: { height: 1.00 } }                  # paint SF

# Waste defaults (can override per item)
default_waste_pct: 0.12

# Pricing provider
pricing_provider: csv
pricing_csv_path: "prices.csv"     # sku,name,price per unit
